export const ORDER_STATUS = Object.freeze({
  ORDER_RECEIVED: 'ORDER_RECEIVED',
  PREPARING: 'PREPARING',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
});

export const ORDER_STATUS_FLOW = Object.freeze([
  ORDER_STATUS.ORDER_RECEIVED,
  ORDER_STATUS.PREPARING,
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.DELIVERED,
]);

export const STATUS_INTERVAL_MS = 10_000;

export const ESTIMATED_DELIVERY_MINUTES = 45;
